# Generated by Django 4.1.7 on 2023-04-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0005_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
    ]
